config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'staffs#index'

  get 'up' => 'rails/health#show', as: :rails_health_check

  resources :staffs
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/staff.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: staffs
#
#  id         :integer          not null, primary key
#  name       :string
#  age        :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Staff < ApplicationRecord
  validates :name, presence: true, length: { in: 2..40 }
  validates :age, presence: true, numericality: { in: 18..70 }

  # after_create_commit -> { broadcast_append_to 'staffs', partial: 'staffs/staff', target: 'staffs', locals: { staff: self } }
  # after_create_commit -> { broadcast_append_to 'staffs', partial: 'staffs/staff', locals: { staff: self } }
  # after_create_commit -> { broadcast_append_to 'staffs' }
  # broadcasts_to ->(_staff) { 'staffs' }
  # broadcasts

  after_create_commit -> { broadcast_prepend_to 'staffs' }
  after_update_commit -> { broadcast_replace_to 'staffs' }
  after_destroy_commit -> { broadcast_remove_to 'staffs' }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/staffs_controller.rb
# frozen_string_literal: true

class StaffsController < ApplicationController
  before_action :set_staff, only: %i[show edit update destroy]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.order('created_at DESC').first(20)
  end

  # GET /staffs/1 or /staffs/1.json
  def show; end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit; end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    if @staff.save
      flash.now[:notice] = 'Staff was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    if @staff.update(staff_params)
      flash.now[:notice] = 'Staff was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy!

    flash.now[:notice] = 'Staff was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_staff
    @staff = Staff.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def staff_params
    params.require(:staff).permit(:name, :age)
  end
end

app/views/layouts/application.html.slim
doctype html

html
  head
    title Rails realtime update with Turbo Stream & Action Cable
    meta name="viewport" content="width=device-width,initial-scale=1"

    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.ico'
    = vite_client_tag
    = vite_javascript_tag 'application'

  body class="bg-neutral-100"
    header class="fixed top-0 z-50 w-full bg-gradient-to-b from-purple-500 to-fuchsia-600 p-4 text-sm lg:text-xl text-white flex justify-center shadow-xl"
      = link_to 'Rails realtime update with Turbo Stream & Action Cable', root_path, class: 'hover:underline'

    main class="px-2 mt-20 max-w-xl mx-auto w-full"
      div class="my-4"
        = link_to 'https://github.com/YutoYasunaga/rails_realtime_update', target: '_blank', class: 'text-blue-600 font-bold hover:underline' do
          i class="fa-brands fa-github"
          span.ml-1 GitHub source code

      #flash
      = yield

    footer class="bg-gray-900 text-gray-100 mt-8 border-t-2 border-stone-600 px-4 py-6"
      div class="flex justify-center"
        span.mr-1 Created by
        = link_to 'Yuto Yasunaga', 'https://yutojp.com', target: '_blank', class: 'font-bold hover:underline'

app/views/partials/_flash_message.html.slim
#flash
  - flash.each do |key, value|
    div class="rails-flash-message flash-message-content flash-message-content--#{key}" = value

  javascript:
      setTimeout(() => {
          document.querySelectorAll('.rails-flash-message').forEach(flashMessageContent => {
              flashMessageContent.classList.add('flash-message-fade-out')
          })
      }, 4000)

app/views/staffs/_form.html.slim
div
  = form_with(model: staff, html: { class: 'flex' }) do |form|
    div class="p-4 w-1/2"
      = form.text_field :name, placeholder: 'Yuto Yasunaga', class: 'w-full'
      - if staff.errors[:name].any?
        div class="text-red-600 text-sm" = "#{Staff.human_attribute_name(:name)} #{staff.errors[:name].first}"

    div class="p-4 w-1/4"
      = form.number_field :age, placeholder: '25', class: 'w-full'
      - if staff.errors[:age].any?
        div class="text-red-600 text-sm" = "#{Staff.human_attribute_name(:age)} #{staff.errors[:age].first}"

    div class="p-4 w-1/4 flex justify-end"
      div
        = form.submit staff.persisted? ? 'Update' : 'Create', class: 'btn'

app/views/staffs/_new_staff_button.html.slim
= turbo_frame_tag 'new_staff' do
  div class="p-2 flex justify-end"
    = link_to 'New staff', new_staff_path, class: 'btn'

app/views/staffs/_staff.html.slim
= turbo_frame_tag staff, class: "[&:nth-child(even)>div]:bg-slate-100 [&:nth-child(odd)>div]:bg-white [&:last-of-type>div]:rounded-b-xl" do
  = turbo_stream_from staff

  div id="#{dom_id staff}" class="border-t border-solid border-gray-300 flex"
    div class="p-2 w-1/2"
      = staff.name
    div class="p-2 w-1/4"
      = staff.age
    div class="px-4 py-2 w-1/4 flex space-x-4 justify-end"
      = link_to edit_staff_path(staff.id) do
        i class="fa-regular fa-pen-to-square"
      = button_to staff, method: :delete, data: { turbo_confirm: "Delete '#{staff.name}'?" } do
        i class="fa-regular fa-trash-can"

app/views/staffs/create.turbo_stream.slim
/ = turbo_stream.prepend('staffs', @staff)
= turbo_stream.replace('new_staff', partial: 'new_staff_button')

= turbo_stream.replace('flash', partial: 'partials/flash_message')

app/views/staffs/destroy.turbo_stream.slim
/ = turbo_stream.remove @staff

= turbo_stream.replace('flash', partial: 'partials/flash_message')

app/views/staffs/edit.html.slim
= turbo_frame_tag @staff do
  = render "form", staff: @staff

app/views/staffs/index.html.slim
= turbo_stream_from 'staffs'

h1 Staffs

div class="mt-4"
  div class="border border-solid border-gray-300 rounded-xl shadow-lg"
    div class="flex font-bold bg-slate-300 rounded-t-xl"
      div class="p-2 w-1/2" Name
      div class="p-2 w-1/4" Age
      div class="p-2 w-1/4"

    div class="bg-slate-100"
      = render 'new_staff_button'

    #staffs
      = render @staffs

app/views/staffs/new.html.slim
= turbo_frame_tag 'new_staff' do
  = render "form", staff: @staff

app/views/staffs/update.turbo_stream.slim
/= turbo_stream.replace(@staff, @staff)

= turbo_stream.replace('flash', partial: 'partials/flash_message')